server:
  port: 8070

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: potato-velog-gateway
  cloud:
    gateway:
      routes:
        - id: potato-velog-user
          uri: http://localhost:8060/
          predicates:
            - Path=/potato-velog-user/**
        - id: potato-velog-board
          uri: http://localhost:8050/
          predicates:
            - Path=/potato-velog-board/**