server:
  port: 8070

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: potato-velog-gateway
  cloud:
    gateway:
      routes:
        - id: potato-velog-user
          uri: lb://POTATO-VELOG-USER
          predicates:
            - Path=/potato-velog-user/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/potato-velog-user/(?<segment>.*), /$\{segment}
        - id: potato-velog-user
          uri: lb://POTATO-VELOG-USER
          predicates:
            - Path=/potato-velog-user/createUser
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/potato-velog-user/(?<segment>.*), /$\{segment}
        - id: potato-velog-user
          uri: lb://POTATO-VELOG-USER
          predicates:
            - Path=/potato-velog-user/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/potato-velog-user/(?<segment>.*), /$\{segment}
        - id: potato-velog-board
          uri: lb://POTATO-VELOG-BOARD
          predicates:
            - Path=/potato-velog-board/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/potato-velog-board/(?<segment>.*), /$\{segment}
            # potato-velog-board로 들어오는것들은 로그인했는지 확인위해서 필터 추가